---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request
    exclude:
    - tag

- name: build-latest
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - BUILD_LATEST=true dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - 2.3-fixes
    event:
      exclude:
      - pull_request
      - tag

- name: upload-latest-2-3
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/static/latest-2.3
    target: releases.rancher.com/ui/latest-2.3
    token:
      from_secret: google_auth_key
  when:
    branch:
    - 2.3-fixes
    event:
      exclude:
      - pull_request
      - tag

- name: build-release
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  environment:
    ENVIRONMENT: production
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
      - tag
    ref:
      include:
      - "refs/tags/v2.3.*"


- name: upload-release
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/static/${DRONE_TAG##v}
    target: releases.rancher.com/ui/${DRONE_TAG##v}
    token:
      from_secret: google_auth_key
  when:
    event:
      - tag
    ref:
      include:
      - "refs/tags/v2.3.*"

- name: upload-release-tar
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/static/${DRONE_TAG##v}.tar.gz
    target: releases.rancher.com/ui/${DRONE_TAG##v}.tar.gz
    token:
      from_secret: google_auth_key
  when:
    event:
      - tag
    ref:
      include:
      - "refs/tags/v2.3.*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
